name: Create release with docker

on:
  workflow_dispatch:
    inputs: 
      version:
        description: "Branch to pull"
        required: true
        default: "testing"
 
jobs:

  buildx:

    runs-on: ubuntu-latest

    steps:
       
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        id: modify
        name: Modify scripts and get version
        run: ./modify.sh 

      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker-unms/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{github.repository}}:latest
            ghcr.io/${{github.repository}}:${{steps.modify.outputs.unms_version}}

