name: Create docker image

on:
  workflow_dispatch:
    inputs: 
      repo:
        description: "Repository to use"
        required: true
        default: "https://github.com/Nico640/docker-unms.git"
      branch:
        description: "Branch to pull"
        required: true
        default: "master"
      
 
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        id: modify
        name: Modify scripts and get version
        run: |
          output=$(./modify.sh ${{github.event.inputs.repo}}) ${{github.event.inputs.branch}})
          output="${output:12}"
          echo ::set-output name=unms_version::$output
      -
        name: version
        run: echo "Version ${{steps.modify.outputs.unms_version}}"
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker-unms
          file: ./docker-unms/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/${{github.repository}}:latest
            ghcr.io/${{github.repository}}:${{steps.modify.outputs.unms_version}}
